refresh_rate: 20
enabled_worlds:
  - "WORLD"
  - "OVERWORLD"
indoor_temperature: 64
peak_temperature_time: 1400
environment_range: 5
in_water_modifier: -24
weather:
  sun_protection: 0.6 # % of sun's temperature blocked by clouds during storms
  modifier: -10 # Temperature change during storms
activity:
  sprinting: 8
  swimming: 0
state:
  burning: 50
  freezing: -50
graduality:
  climate: 0.12
  environment: 0.15
  water: 0.75
  clothing: 0.25
  tool: 0.7
  activity: 0.02
  state: 0.8
wetness:
  modifier: -16
  max: 60
  increment: 5
  decrement: 1
  enable_degradation: true
resistance:
  ideal: 75 # The more you resist, the closer to this temperature you get (In Fahrenheit)
  potion_effects: # The maximum and minimum you will ever reach while resisting temperature with potions
    max_temperature: 90
    min_temperature: 10
    list:
      fire_resistance: 0.7
      night_vision: -0.7
      resistance: 1.55
  enchantments:
    list:
      fire_protection: 0.02
  hunger:
    midpoint: 3.5
    resistance: 0.15
    vulnerability: 0.4
  thirst:
    midpoint: 3.5
    resistance: 0.15
    vulnerability: 0.4
debuffs:
  grace_period: 30
  140:
    - "BURNING"
  129:
    - "BLINDNESS:1"
  124:
    - "NAUSEA:1"
  108:
    - "HUNGER:1"
  41:
    - "SLOWNESS:1"
  29:
    - "WEAKNESS:1"
  -13:
    - "MINING_FATIGUE:1"
  -22:
    - "SLOWNESS:2"
    - "DARKNESS:1"
  -32:
    - "FREEZING"
clothing:
  default:
    warmth: 2
    resistance: -0.025
  leather:
    warmth: 5
    resistance: -0.3
  chainmail:
    warmth: 0
    resistance: 0
  golden:
    warmth: 1.7