name: 'Temperature'
version: '${project.version}'
main: me.gnago.temperature.TemperaturePlugin
api-version: 1.13
commands:
  showbaralways:
    description: Toggles whether the temperature bar is shown under any circumstance. Affects all players.
    permission: server.admin