name: 'Gnemperature'
description: 'Temperature plugin that calculates a player''s temperature using various factors and applies debuffs at extremes.'
version: '${project.version}'
main: me.gnago.gnemperature.GnemperaturePlugin
api-version: 1.13
softdepend:
  - "PlaceholderAPI"
  - "ThirstBar"